lista = []
p1 = input("Qual a palavra:")
lista.append (p1)
p2 = input("Qual a segunda:")
lista.append (p2)
p3 = input("Qual a terceira:")
lista.append (p3)
p4 = input("Qual a quarta:")
lista.append (p4)
p5 = input ("Qual a ultima:")
lista.append (p5)
print (lista)
lista.pop(4)
print (lista)
lista.pop(3)
print (lista)
lista.pop(2)
print (lista)
lista.pop(1)
print (lista)
lista.pop(0)
print (lista)